version: '3.7'

services:
  eshop.api:
    image: ${DOCKER_REGISTRY-}eshopapi
    build:
      context: ../server
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://*:5000
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"